services:
  pcos-dev:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    container_name: pcos_poc
    volumes:
      - ./src:/app/src
      - ./notebooks:/app/notebooks
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
      - ./scripts:/app/scripts
      - ./config.yaml:/app/config.yaml
      - ./kaggle.json:/root/.kaggle/kaggle.json
    ports:
      - "8888:8888"  # Jupyter
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      bash -c "
        chmod 600 /root/.kaggle/kaggle.json &&
        jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' &
        tail -f /dev/null
      " 